/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonAside: typeof import('./src/components/CommonAside.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    EpAim: typeof import('~icons/ep/aim')['default']
    EpEdit: typeof import('~icons/ep/edit')['default']
    EpMessageBox: typeof import('~icons/ep/message-box')['default']
    EpPlus: typeof import('~icons/ep/plus')['default']
    EpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    IconCreditCard: typeof import('~icons/ep/credit-card')['default']
    IconDelete: typeof import('~icons/ep/delete')['default']
    IconEdit: typeof import('~icons/ep/edit')['default']
    IconEpAim: typeof import('~icons/ep/aim')['default']
    IconInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpAim: typeof import('~icons/ep/aim')['default']
    IEpApple: typeof import('~icons/ep/apple')['default']
    IEpHouse: typeof import('~icons/ep/house')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpValue: typeof import('~icons/ep/value')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
